use_frameworks!

target 'PhotoKit_Example' do
  pod 'XPhotoKit', :path => '../'

  pod 'SDWebImage'
  pod 'XPhotoKit', '0.1.14'
  pod 'LookinServer', :configurations => ['Debug']

  target 'PhotoKit_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
